# Generated by Django 6.0.3 on 2026-03-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_account_client_alter_balance_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='address',
            new_name='street_address',
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(default='Unknown', max_length=10),
            preserve_default=False,
        ),
    ]
